apiVersion: v1
kind: Service
metadata:
  name: {{ include "switch-scraper.fullname" . }}
  labels:
    {{- include "switch-scraper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: prom-exporter
  selector:
    {{- include "switch-scraper.selectorLabels" . | nindent 4 }}
