{{- with .Values.env.PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "switch-scraper.fullname" $ }}-password
  labels:
    {{- include "switch-scraper.labels" $ | nindent 4 }}
type: Opaque
data:
  password: {{ $.Values.env.PASSWORD | b64enc }}
{{- end }}